* July
First month at work!!
I will arrange into list later.
** 04.07.2016
Getting familiar with the system, studying how to use emacs org-mode better.
Getting the source code and start searching for information about the dtrack
system.
** 05.07.2016
Reconfigured part of the emacs configuration. Did a small test of combining MiddleVR
with Unity, on the desktop.

MiddleVR seems to be simply configuring the hardware systems for the softwares.
The only thing left for deploying a fully functioning test is to findout how to configure
the CAVE system. Or find out where to download the configuration file.

Tricky thing is that MiddleVR website needs VPN to log onto in Singapore, I'm not sure why
but next time I will have to install VPN.
*** DONE Install VPN on all computers
    CLOSED: [2016-07-12 Tue 12:32]
    - State "DONE"       from "TODO"       [2016-07-12 Tue 12:32]
** 12.07.2016
Finished installing unity to the main computer of the server room. Fixed stereo imaging problems.
Will start doing tests on the system.
** 13.07.2016
Finished testing middleVR and unity. Simple virtual environment.
** 14.07.2016
** 19.07.2016
Tested simple scripts in controlling objects in unity. Installed some tool called
Blender. Seems to be useful.

Also I added Wangxin's UR10 arm 3d objects in the testing project. Will start testing
arm controlling in local environment.
** 21.07.2016
Finished basic layouts of the website. Moved back to emacs prelude configuration.
** 25.07.2016
Trying to finish the website.
** 31.07.2016
Finished basic layouts of the website. Trying to make the kinematics work. 
* August
Second month. Starting testing in VR room.
** Tue Aug  2 11:40:57 2016
Testing simple hand position tracking. 
** 8/12/2016 3:53:02 PM
Finished running mountain environment in four screens but not in 3d. We 
will be looking into the tracking system instead of fixing this issue in the 
next couple weeks.
** 8/17/2016 2:15:38 PM
Installed gym environment in windows for openAI. Tested basic stick model of 
reinforcement learning in windows.
 
Simple test on how to control the spinning speed of the robot arm. Spinning in 
update is a time series process.
** Sat Sep  3 17:28:07 2016
 Finished the modeling for IK(which was totally easy for anyone it's just I was too lazy this month).
Still working on the learning of reinforcement learning.
