* July
First month at work!!
I will arrange into list later.
** 04.07.2016
Getting familiar with the system, studying how to use emacs org-mode better.
Getting the source code and start searching for information about the dtrack
system.
** 05.07.2016
Reconfigured part of the emacs configuration. Did a small test of combining MiddleVR
with Unity, on the desktop.

MiddleVR seems to be simply configuring the hardware systems for the softwares.
The only thing left for deploying a fully functioning test is to findout how to configure
the CAVE system. Or find out where to download the configuration file.

Tricky thing is that MiddleVR website needs VPN to log onto in Singapore, I'm not sure why
but next time I will have to install VPN.
*** DONE Install VPN on all computers
    CLOSED: [2016-07-12 Tue 12:32]
    - State "DONE"       from "TODO"       [2016-07-12 Tue 12:32]
** 12.07.2016
Finished installing unity to the main computer of the server room. Fixed stereo imaging problems.
Will start doing tests on the system.
** 13.07.2016
Finished testing middleVR and unity. Simple virtual environment.
** 14.07.2016
** 19.07.2016
Tested simple scripts in controlling objects in unity. Installed some tool called
Blender. Seems to be useful.

Also I added Wangxin's UR10 arm 3d objects in the testing project. Will start testing
arm controlling in local environment.
** 21.07.2016
Finished basic layouts of the website. Moved back to emacs prelude configuration.
** 25.07.2016
Trying to finish the website.
