* Repository for SiNAPSE


** About This Repo
   To integrate everything that I do during working at SiNAPSE. In the website folder there is
   a simple Angular website that I made for SiNAPSE Neuromorphic Robitc group. And the latex folder 
   contains slides and papers that I wrote.

** Website
   The website folder contains the angularjs seed project. I will be making modification 
and designing later.

** Crawler
   Crawler folder is something that I have written to crawl all the academic papers from the 
internet. So far I have only crawled CVPR. Will add something later if necessary.

t1NmGarahTJCj7ckyTkozHPtHLJd6vzPLb2
** Setting Up Systems
There will be a folder for main project later and I will be moving this section later. 

PAppropriate setup of the environment is introduced in the =Unity_MiddleVR_talk.pdf= file. 
I will be adding more docs later.
** Continuous Integration
   More integration should be added in order to make the development more professional. 

** LICENCE 
   Will add licence later if necessary.
