######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 27 11:57:52 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += artclient.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += artclient.cpp main.cpp mainwindow.cpp
