######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 27 11:57:52 2016
######################################################################

TEMPLATE = app
TARGET =
TARGET.path = .
DEPENDPATH += .
INCLUDEPATH += .
INSTALLS += TARGET

QT += charts core gui network

# Input
HEADERS += artclient.h mainwindow.h \
    gesvisulizer.h
FORMS += mainwindow.ui
SOURCES += artclient.cpp main.cpp mainwindow.cpp \
    gesvisulizer.cpp

