#+TITLE: Tutorial for Robotics and Graphics
#+AUTHOR: Pan An
#+OPTIONS: toc:2


#+LATEX: \newpage
#+BEGIN_abstract
This documentation presents tutorials for all the projects that might concern our group in SiNAPSE. All the source code and resources for the projects presented here can be found on Github. In the chapter of fluid simulation, rendering models are provided in order to help with further optimization of the platform.
#+END_abstract

#+LATEX: \newpage
* iLimb Controlling
The iLimb controlling is composed by several different part:
- Core Code Uploading
- Keyboard Controlling
- Programming Interface

For more advanced features, read the source code of /Core/. 

** Prior Steps
Our experimental set up consists of a robotic hand ~iLimb~, an ARM based development board and batteries. Before running anything on the setup, you need to charge the battery.

Long press the plastic button attached to the batteries until the there are blue LEDs glowing.  

The iLimb manual provided in our group should have a concise description of all the software needed for development board configuration. When the development environment is set up, make sure the connection of the board to the hand is correct by checking the images in this folder. 

** Keyboard Controlling 
iLimb Core contains the core project for iLimb development board provided together with iLimb robot hand. Please refer to the iLimb devboard manual for details of development environment setup. 

In order to run keyboard control commands, you need to have a serial port terminal installed. In this tutorial we choose to use ~Teraterm~. 

- Turn on the development board, you will see green lights on the board. If not, slightly adjust the battery cable until it does.
- Connect the USB of the burner board to a computer with complete software setup.
- Copy and paste the ~Nucleo_LDA.bin~ in /Core/ folder to the disk of the board.

By now the development board should be able to work with programming and keyboard interfaces. 

Follow steps below to test:
1. Open Teraterm, check to ~Serial~ radius and select the port of the burner. Here we assume that it is ~COM1~. Click "OK". 
2. Go to Setup -> Serial port and change the baud rate to 115200.
3. Turn the development off and on, you will see a sequence of messages. Click "Y" to select new configuration. Click 2 to choose keyboard control, then press "Enter".
4. There will be two initialization moves, normally I will choose to wait for it to finish. When the hand finishes initialization testing, try the keys in the following table.



*** Burn Core Project File

| Key        | Pressed Action                                             |
| 0	  | Normal grip                                                |
| 1	  | Standard Precision Pinch Closed                            |
| 2	  | Standard Tripod Closed                                     |
| 3	  | Thumb Park, continuous                                     |
| 5	  | Lateral grip                                               |
| 6 	 | Index Point (trigger)                                      |
| 7	  | Standard Precision Open                                    |
| 9	  | Thumb Precision Closed                                     |
| a	  | Thumb Precision Open                                       |
| b	  | Thumb Tripod Open                                          |
| d	  | Standard Tripod Open                                       |
| e	  | Thumb Tripod Open                                          |
| f	  | Donning/doffing  glove                                     |
| o	  | Open all fingers (depends on active fingers in that grip)  |
| c	  | Close all fingers (depends on active fingers in that grip) |
| t	  | Move thumb individually                                    |
| i	  | Move index finger individually                             |
| m	  | Move middle finger individually                            |
| r	  | Move ring finger individually                              |
| p	  | Move pinky finger individually                             |
| s	  | Stop all movement                                          |
| x	  | Stop movement of wrist                                     |
| y	  | Move wrist one direction                                   |
| z	  | Move wrist other direction (depends on cable orientation)  |

** Programming Interface
There are several ways to manipulate the robot hand with programming. Easiest way is to send keyboard commands from serial port with any programming language. The ~iLimb~ repository contains documents for source code manipulation(which is a docx file). 

To simply control the hand with MATLAB programs, refer to the ~initialization.m~ in ~iLimb~ repository.


* Fluid Simulation
The fluid simulation engine, was originally started to simulate under water scenarios with robots operating. Though faced with unsolved mathematical and physical problems, turbulence for example, the engine still provides predictions of an operation without really sending robots down there. The simulation engine is supposed to help defining scenes, testing and predicting the effect of environmental conditions(e.g., water flow) on robots. Since the models are involved are based on finite element methods, it is also possible to predict haptic sensors signals on a robot hand.

Particl-in-cell(PIC) method is the first method developed and used primarily for fluid mechanics.  Currently we are still seeking to duplicate the result of paper [[https://www.math.ucla.edu/~jteran/papers/PGKFTJM17.pdf][/Multi Species Simulation of Porous Sand and Water Mixture/]]. The simulation is based on ~material point method~ (MPM). MPM is one of the latest developments in PIC. Our project contains implementations both for PIC and MPM. The implementation is heavily based on the [[https://github.com/doyubkim/fluid-engine-dev][~fluid-engine-dev~]]. 

** Models

